
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: test-backend
    ports:
      - "3000:3000"
    env_file:
      - .env
    command: sh -c "pnpm start"